Update Workshop Week 1.ipynb
unable to complete Data and Plotting section as due to "module not found" errors
ModuleNotFoundError: No module named 'pandas'